### ISSUE TITLE
Java version of book site not working

### ISSUE THREAD

**Issue by Thoughtscape2014** [regueiro/calibre-server-docker#6]
I set up everything as per the instructions. I get this message and a neverending message bar that says:

Loading, please wait…
You can also use a simple, non-javascript version of this site: here

Nothing ever happens. I click 'here' and it goes to the correct simple/mobile version which is awesome but when I click the epub or text button but it keeps saying 'refused to connect'. No firewall in place for testing.

Any ideas?

**Comment by regueiro** [comment]
I haven't used calibre in years, this image is probably broken.

You should try with another image. https://hub.docker.com/r/linuxserver/calibre or https://hub.docker.com/r/linuxserver/calibre-web seem well mantained.
